# Generated by Django 5.0.6 on 2024-08-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_description',
            field=models.TextField(default="The first step for every child. We lovingly nurture them as they begin to explore and understand the beautiful world around them. Our nursery class features specially designed programs and assignments that enhance children's logical thinking and prepare them for future learning."),
        ),
    ]
