# Generated by Django 5.0.6 on 2024-08-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(upload_to='teacher_pictures/')),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('is_student', models.BooleanField(default=False)),
            ],
        ),
    ]
