# Generated by Django 5.0.6 on 2024-08-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_image', models.ImageField(upload_to='about_us/')),
                ('small_image', models.ImageField(upload_to='about_us/')),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
            ],
        ),
    ]
