# Generated by Django 5.0.6 on 2024-08-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='objectives',
        ),
    ]
