# Generated by Django 5.0.6 on 2024-08-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_remove_aboutus_objectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='parent_image/')),
                ('opnion', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
