# Generated by Django 5.0.6 on 2024-08-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0003_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='small_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='about_us/'),
        ),
    ]
