# Generated by Django 5.0.6 on 2024-08-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0004_alter_aboutus_small_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='small_image',
            field=models.ImageField(upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='parent_image/'),
        ),
    ]
