# Generated by Django 5.0.6 on 2024-08-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0005_alter_aboutus_small_image_alter_parents_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='image',
            field=models.ImageField(blank=True, default='parent_image/default.png', upload_to='parent_image/'),
        ),
    ]
