# Generated by Django 5.0.6 on 2024-08-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0006_alter_parents_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='contact_number',
            field=models.CharField(default='9819464437', max_length=15),
        ),
    ]
