# Generated by Django 5.0.6 on 2024-08-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0007_parents_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_address', models.TextField()),
                ('student_grade', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
